// Load the two instances' vendored kind manifests and tag registries, and work out what is
// SHARED between them versus what each one adds.
//
// The catalogs' whole job is to make that split legible: the pattern's claim is that a
// substrate transfers and the differences localize, and a claim like that is only worth
// anything if you can see the diff. So "shared" is COMPUTED here — a kind is substrate
// because both instances declare it, a facet is shared because both registries carry it —
// never asserted by hand in prose that would quietly stop being true.

import fs from 'node:fs';
import path from 'node:path';

import { parseKindManifest } from '@galaxy-foundry/kind-manifest';
import type {
  Companion,
  KindManifest,
  ManifestKind,
  ManifestSource,
} from '@galaxy-foundry/kind-manifest';
import { parseTagRegistry } from '@galaxy-foundry/tag-registry';
import type { Facet, TagRegistryFile } from '@galaxy-foundry/tag-registry';

const DATA_DIR = path.resolve('src/data/instances');

// Both formats are the instances', not ours. This file used to carry a hand-written copy of
// each — a fourth copy of the manifest types, and a fifth encoding of the tag-registry shape
// — beside one in each instance and one in the prose spec.
export type {
  Companion,
  KindManifest,
  ManifestField,
  ManifestKind,
  NoteShape,
} from '@galaxy-foundry/kind-manifest';
export type { Facet, TagRegistryFile } from '@galaxy-foundry/tag-registry';

/**
 * A manifest as this site holds it: vendored, so it always carries a full source envelope.
 *
 * The shared format leaves `source` optional — a producer declares only `repo` and `path`,
 * and an older one declares neither. Everything under src/data/ came through the vendoring
 * script, which validates and stamps the revision, so the catalog can rely on all three
 * being present. `loadManifest` is where that reliance is checked rather than assumed.
 */
export interface VendoredManifest extends KindManifest {
  source: Required<ManifestSource>;
}

export interface Instance {
  slug: string;
  /** Display name, and the wiki-linkable page in content/instances/. */
  title: string;
  manifest: VendoredManifest;
  tags: TagRegistryFile;
}

/**
 * Read one vendored manifest, validating it against the shared format.
 *
 * The file is generated by another repository and copied in by a script. Casting it to an
 * interface would let a manifest that stopped matching the format render as a page of blank
 * cells instead of failing where the problem actually is.
 */
function loadManifest(slug: string): VendoredManifest {
  const file = path.join(DATA_DIR, slug, 'kinds.json');
  const manifest = parseKindManifest(JSON.parse(fs.readFileSync(file, 'utf8')));
  const source = manifest.source;
  if (!source?.revision) {
    throw new Error(`${file}: vendored manifest has no source revision — re-run sync:instances`);
  }
  return { ...manifest, source: { ...source, revision: source.revision } };
}

/** Declaration order is instance order everywhere: #1 first. */
const INSTANCE_TITLES: Record<string, string> = {
  'galaxy-workflow-foundry': 'Galaxy Workflow Foundry',
  'statistical-genomics-foundry': 'Statistical Genomics Foundry',
};

/**
 * Read one vendored tag registry, validating it against the shared format.
 *
 * Same reasoning as `loadManifest`: this is another repository's file, and both instances
 * used to do `yaml.load(...) as TagRegistryFile` and meet a malformed registry as an
 * `undefined` somewhere downstream. Parsing refuses a missing `facets` block, a facet with
 * no label or description, a tag with no gloss, and — the one no single instance could
 * catch — a tag two facets both declare, which would file it under one facet on the browse
 * page while the other silently listed it too.
 */
function loadTags(slug: string): TagRegistryFile {
  const file = path.join(DATA_DIR, slug, 'meta_tags.yml');
  return parseTagRegistry(fs.readFileSync(file, 'utf8'), file);
}

export function loadInstances(): Instance[] {
  return Object.keys(INSTANCE_TITLES).map((slug) => ({
    slug,
    title: INSTANCE_TITLES[slug],
    manifest: loadManifest(slug),
    tags: loadTags(slug),
  }));
}

export interface KindRow {
  kind: string;
  /** The instances declaring this kind, in instance order. */
  present: Instance[];
  /** Per-instance detail, present only where the instance declares the kind. */
  by: Record<string, ManifestKind | undefined>;
  /** Declared by EVERY instance — the empirical definition of substrate. */
  shared: boolean;
}

/**
 * One row per distinct `type:` value across the instances, substrate first.
 *
 * `shared` is computed, not read from the manifests' own `layer` field. The two are meant to
 * agree, and where they do not, this function is right and the manifest is a claim its author
 * has not yet earned — which is worth surfacing rather than smoothing over.
 */
export function kindRows(instances: Instance[]): KindRow[] {
  const names = [...new Set(instances.flatMap((i) => i.manifest.kinds.map((k) => k.kind)))];
  const rows = names.map((kind) => {
    const by: Record<string, ManifestKind | undefined> = {};
    for (const instance of instances) {
      by[instance.slug] = instance.manifest.kinds.find((k) => k.kind === kind);
    }
    const present = instances.filter((i) => by[i.slug]);
    return { kind, present, by, shared: present.length === instances.length };
  });
  return rows.sort(
    (a, b) =>
      Number(b.shared) - Number(a.shared) ||
      b.present.length - a.present.length ||
      a.kind.localeCompare(b.kind),
  );
}

/** A kind's manifest `layer` disagreeing with what the instances actually declare. */
export function layerDisagreements(rows: KindRow[]): string[] {
  return rows
    .filter((row) =>
      row.present.some((i) => (row.by[i.slug]!.layer === 'substrate') !== row.shared),
    )
    .map((row) => row.kind);
}

export interface FacetRow {
  key: string;
  present: Instance[];
  by: Record<string, Facet | undefined>;
  shared: boolean;
}

/** One row per distinct facet key across the registries, shared first. */
export function facetRows(instances: Instance[]): FacetRow[] {
  const keys = [...new Set(instances.flatMap((i) => Object.keys(i.tags.facets ?? {})))];
  const rows = keys.map((key) => {
    const by: Record<string, Facet | undefined> = {};
    for (const instance of instances) by[instance.slug] = instance.tags.facets?.[key];
    const present = instances.filter((i) => by[i.slug]);
    return { key, present, by, shared: present.length === instances.length };
  });
  return rows.sort(
    (a, b) => Number(b.shared) - Number(a.shared) || a.key.localeCompare(b.key),
  );
}

export const tagCount = (instance: Instance): number =>
  Object.values(instance.tags.facets ?? {}).reduce(
    (n, f) => n + Object.keys(f.values ?? {}).length,
    0,
  );

/** One companion filename, and what each instance declaring the kind says about it. */
export interface CompanionRow {
  file: string;
  /** Per-instance declaration, absent where that instance does not declare this companion. */
  by: Record<string, Companion | undefined>;
  /** Declared by EVERY instance that declares the kind. */
  shared: boolean;
  /**
   * Shared, and every declaring instance agrees on requirement AND disposition.
   *
   * Kept apart from `shared` because they are different claims. `guidance.md` is `required` for
   * a paper and `optional` for a book chapter in the same instance; two instances splitting that
   * way on one kind would be a real difference, and a table that reported only the filename
   * would render it as a match.
   */
  identical: boolean;
}

/**
 * One row per distinct companion across the instances declaring the kind, shared first.
 *
 * Same discipline as `kindRows`: shared is COMPUTED. A companion arriving in both foundries is
 * the strongest transfer evidence this site has — a layout is not something you copy without
 * also copying the practice that produced it — so it is worth exactly as much as the derivation
 * behind it, and no more.
 */
export function companionRows(row: KindRow): CompanionRow[] {
  // Only directory-shaped instances declare a layout. A companion named on a file-shaped kind
  // has no directory to sit in — `companionsOf` refuses to build one, so no instance can emit
  // it — and rendering it as this kind's layout would be reporting a claim nobody made.
  const declaring = row.present.filter((i) => row.by[i.slug]!.shape === 'directory');
  const files = [...new Set(declaring.flatMap((i) => row.by[i.slug]!.companions.map((c) => c.file)))];
  const rows = files.map((file) => {
    const by: Record<string, Companion | undefined> = {};
    for (const instance of declaring) {
      by[instance.slug] = row.by[instance.slug]!.companions.find((c) => c.file === file);
    }
    const declared = declaring.map((i) => by[i.slug]).filter((c): c is Companion => Boolean(c));
    const shared = declared.length === declaring.length && declaring.length > 1;
    return {
      file,
      by,
      shared,
      identical:
        shared &&
        declared.every(
          (c) =>
            c.requirement === declared[0].requirement && c.disposition === declared[0].disposition,
        ),
    };
  });
  return rows.sort(
    (a, b) => Number(b.shared) - Number(a.shared) || a.file.localeCompare(b.file),
  );
}

/**
 * Kinds whose notes are flat files in one instance and directories in another.
 *
 * There is no third value to guard against. This used to skip instances declaring no shape, on
 * the reasoning that an older manifest is silent rather than different — but the format makes
 * `shape` required, so a silent manifest does not parse and never arrives here. The guarantee
 * belongs to the reader; restating it here only implied it might not hold.
 */
export function shapeDifferences(rows: KindRow[]): string[] {
  return rows
    .filter((row) => new Set(row.present.map((i) => row.by[i.slug]!.shape)).size > 1)
    .map((row) => row.kind);
}

/** Fields required by EVERY instance that declares the kind — the kind's shared envelope. */
export function sharedRequiredFields(row: KindRow): string[] {
  if (row.present.length < 2) return [];
  const sets = row.present.map(
    (i) => new Set(row.by[i.slug]!.fields.filter((f) => f.required).map((f) => f.name)),
  );
  return [...sets[0]].filter((name) => sets.every((s) => s.has(name))).sort();
}
